### ISSUE TITLE
Enhance/ Make useful Reporting Graphs

### ISSUE THREAD

**Issue by MattGaiaver** [DigiThinkIT/frappe_starter_theme#24]
As a CEO/Sales manager, it is currently difficult for me to run meaningful report graphs for analysis.

I would prefer the graphs to be formatted so that they are more readable at-a-glance which is the whole point of the graph.

Currently the item names are truncated/abbreviated so that I can only hover over the graph to read the item name and it's value and it look like this (it would also be helpful if the value had 1,000 comma formatting and a $ if it's a dollar value):  

![Screen Shot 2018-11-09 at 10.28.06 AM.png](https://images.zenhubusercontent.com/5b606e56d6768d6255917cbf/4c390f92-9471-4e12-9021-c8188ecf3dc9)

Here is an example of a useful graph (not the look/format but the labeling):
![Readablegraphchart.png](https://images.zenhubusercontent.com/5b606e56d6768d6255917cbf/860237d0-e5b8-4949-bedb-c35f5c753920)

Finally... If there was a print icon above the chart so that I could easily extract the chart in a pdf full page format this would be the final step to fully utilizing the chart feature for expert analysis and professional looking presentations.

**Comment by Alchez** [comment]
Issue moved to [DigiThinkIT/bloomstack #276](https://github.com/DigiThinkIT/bloomstack/issues/276) via [**ZenHub**](https://www.zenhub.com/)
