### ISSUE TITLE
Extraction Process from MJ Platform videos and screenshots

### ISSUE THREAD

**Issue by MattGaiaver** [DigiThinkIT/frappe_starter_theme#25]
As a production manager I need to be able to take raw material/flower and working through processing multiple batches then extract, winterize and distill the oil to a finished item that can then be used in the manufacturing work flow as an ingredient in making finished goods such as vape cartridges, brownies, and capsules.

I will put all resources:  Detla 9's existing workflow and all screen shots on my Google Drive and then share with the team.

Here is a link to the video for E&I Processing Types and Extractions:  https://vimeo.com/266886960

Here's the Nuclino link to my notes and screen shots of the above video:
https://app.nuclino.com/DigiThinkIt/BloomStack/EI-Processing-Types-Extractions-5f3f6241-083b-40cd-ba38-3c8a48c0d80e

Here is the link to the video for Assemblies and Ingredients: https://vimeo.com/266886825

Here's the Nuclino link to my notes and screen shots of the above video:
https://app.nuclino.com/DigiThinkIt/BloomStack/EI-Assemblies-and-Ingredients-af34e138-eed3-4aa7-bb74-a1bad6d43bdf

Here is the link to ALL the MJPlatform video tutorials:  https://vimeo.com/user8358322

**Comment by Alchez** [comment]
Issue moved to [DigiThinkIT/bloomstack #275](https://github.com/DigiThinkIT/bloomstack/issues/275) via [**ZenHub**](https://www.zenhub.com/)
