### ISSUE TITLE
Ability to create a Profit and Loss Statement for any day or week.

### ISSUE THREAD

**Issue by MattGaiaver** [DigiThinkIT/frappe_starter_theme#26]
Currently when you create a Profit and Loss Statement the only options are for Monthly, Quarterly, Half-Yearly and Yearly.  Delta9 would like to be able to pull out a weekly date range AND a Daily PnL.

![PnL Statement.png](https://images.zenhubusercontent.com/5b606e56d6768d6255917cbf/d96d128c-8966-4116-aa90-08dbcef3fda1)

**Comment by Alchez** [comment]
Issue moved to [DigiThinkIT/bloomstack #274](https://github.com/DigiThinkIT/bloomstack/issues/274) via [**ZenHub**](https://www.zenhub.com/)
